### ISSUE TITLE
Is this crate dead?

### ISSUE THREAD

**Issue by daniellivingston** [rust-lang/cmake-rs#162]
There are few signs of life in this repo. Is it still being actively maintained? This is important for determining whether it should be included in production code or whether another crate/approach should be taken.

**Comment by thomcc** [comment]
It's nominally still alive, but I believe the team responsible for maintaining it lacks a ton of `cmake` experience, so a lot of the maintenance is on the passive side.

**Comment by glebpom** [comment]
It would be nice to release the new version, with already merged changes

**Comment by emk** [comment]
We are seeing build breakage on Ubuntu 18 systems, which use a version of `cmake` that does not support `--parallel`. [This fix](https://github.com/rust-lang/cmake-rs/pull/146) has been merged since May, but not yet released. I would be happy to help make a new release of this crate if nobody else has the time!

We still have Ubuntu 18 systems running on Dell Linux developer laptops, because upgrading from the vendor-supported OS version is a bit risky and may break things that Dell had working nicely under the original Ubuntu version.

**Comment by thomcc** [comment]
I should have access to this crate now, so I'll cut a release with the currently merged changes after work today.

**Comment by daniellivingston** [comment]
So happy to hear that! Thank you for your work maintaining this and other crates @thomcc .
