### ISSUE TITLE
Android: Unknown processor CMAKE_SYSTEM_PROCESSOR=arm

### ISSUE THREAD

**Issue by MarginGitHub** [rust-lang/cmake-rs#175]
When this happens，CMAKE_SYSTEM_PROCESSOR should be armv7-a，not arm

**Comment by adwhit** [comment]
For anyone arriving here after trying to upgrade to NDK `v27`, I think there is now a separate issue that has surfaced that gives a similar error. The root cause is actually the ABI values not being set at all within cmake due to a change in configuration. See: https://github.com/android/ndk/issues/2049
